# BetterStaffChat

# Copyright (c) 2021 AusTech Development Team
# Licensed under GNU General Public License v3

# Github profile: https://github.com/AusTechDev/
# Spigot Profile: https://www.spigotmc.org/members/919057/
# Discord Server: https://austech.dev/to/support

staffchat:
  # PlaceholderAPI is supported only on Spigot
  # Placeholders for both spigot and bungeecord:
  # %player_name% - The player's name, %message% - The message, %server% - The server the player is on (ONLY BUNGEE)
  # %luckperms_prefix% - The prefix of the player from LuckPerms, %luckperms_suffix% - The suffix of the player from LuckPerms
  format: "&8[&dS&8] &7%player_name%&8: &f%message%"

  # Putting whatever is below before your message will send it to staffchat
  # e.g # hello there
  prefix: "# " # Set to "" to disable

  # Set the name of the sender when console runs /staffchat <message>
  console-replacement: "Console"

  # Set the UUID of the console when %uuid% is used in embeds
  console-uuid-replacement: "f78a4d8d-d51b-4b39-98a3-230f2de0c670"

  # Set the name of the sender when console runs /staffchat <message>
  # ONLY BUNGEE
  console-server-replacement: "Global"

  # Whether or not to send staffchat messages to console
  log-to-console: true

  # If a staff member puts color codes in their message, it will remove them if the below is true.
  strip-color-codes: false

  # Changes the display name of servers on Bungeecord. Color codes supported
  server-replacement: # Format - servername: "Displayname"
    hub: "Hub" # Make sure that the first value is the one equal to in the bungeecord config.yml

  # The message that shows when someone has "betterstaffchat.messages.join" joins the network
  # PlaceholderAPI is supported only on Spigot
  # Placeholders for both spigot and bungeecord:
  # %player_name% - The player's name, %server% - The server the player is on (ONLY BUNGEE)
  # %luckperms_prefix% - The prefix of the player from LuckPerms, %luckperms_suffix% - The suffix of the player from LuckPerms
  join: "&8[&dS&8] &7%player_name% &fjoined &7the network." # Set to "" to disable

  # The message that shows when someone has "betterstaffchat.messages.leave" leaves the network
  # PlaceholderAPI is supported only on Spigot
  # Placeholders for both spigot and bungeecord:
  # %player_name% - The player's name, %server% - The server the player is on (ONLY BUNGEE)
  # %luckperms_prefix% - The prefix of the player from LuckPerms, %luckperms_suffix% - The suffix of the player from LuckPerms
  leave: "&8[&dS&8] &7%player_name% &fleft &7the network." # Set to "" to disable

  # The message that shows when someone has "betterstaffchat.messages.switch" switches between servers/worlds
  # PlaceholderAPI is supported only on Spigot
  # Note, if on bungee it will show the server, however on spigot it will show the world.
  # %player_name% - The player's name, %from% - The server/world the player left, %to% - The server/world the player joined
  # %luckperms_prefix% - The prefix of the player from LuckPerms, %luckperms_suffix% - The suffix of the player from LuckPerms
  switch: "&8[&dS&8] &7%player_name% &fswitched &7from &f%from% &7to &f%to%" # Set to "" to disable

  # The message that is shown when staff chat messages are toggled on with /mutestaffchat
  # /mutestaffchat required permission betterstaffchat.mutestaffchat
  mute-off: "&8[&dS&8] &7Your staff chat is now &aenabled&7."

  # The message that is shown when staff chat messages are toggled off with /mutestaffchat
  # /mutestaffchat required permission betterstaffchat.mutestaffchat
  mute-on: "&8[&dS&8] &7Your staff chat is now &cdisabled&7."

  # The message that is shown when all the player's messages go to the staffchat with /togglestaffchat
  # /togglestaffchat required permission betterstaffchat.togglestaffchat
  toggle-off: "&8[&dS&8] &7All your messages will &cno longer&7 go to staffchat."

  # The message that is shown when staff chat messages are toggled on with /mutestaffchat
  # /mutestaffchat required permission betterstaffchat.mutestaffchat
  toggle-on: "&8[&dS&8] &7All your messages will &anow&7 go to staffchat."

discord:

  # If you need help, we're here to assist you at https://austech.dev/to/support

  # Don't enable if webhook is enabled below
  bot:
    enabled: false

    # The token of the Discord bot. If you need help setting it up we're here to assist you at https://austech.dev/to/support
    token: "N/A"

    # What the bot is doing in its status, e.g Playing with staffchat
    activity: "with staffchat"

    # The different types of activities (Must be in caps)
    # - PLAYING, WATCHING, LISTENING
    activity-type: "PLAYING"

    # The channels that staff messages are sent to
    # Format - GuildID: ChannelID
    channels:
      - "N/A: N/A"


  # Don't enable if bot is enabled above
  webhook:
    enabled: false

    # The webhook URL. If you need help setting it up we're here to assist you at https://austech.dev/to/support
    url: ""

  discord-messages:

    # The format in game, for when someone sends a message in Discord
    # Available placeholders: %username%, %discriminator% - The 4 numbers in the username
    # %nickname% - The nickname on Discord
    name-format: "%username%#%discriminator%"

    embed:
      # Whether or not the message sent to Discord should be an embed
      # true for yes, false for no.
      enabled: true

      # The text that is at the bottom of the embed
      # %player_name% - The player's name, %uuid% - The player's UUID, %server% - The server the player is on (ONLY BUNGEE)
      embed-footer: "BetterStaffChat" # Setting this to "" will disable this and the icon.

      # The little icon next to the footer
      # %player_name% - The player's name, %uuid% - The player's UUID, %server% - The server the player is on (ONLY BUNGEE)
      embed-footer-icon: "https://crafatar.com/avatars/%uuid%?overlay" # Set to "" to disable

      # The color of the embed, MUST be a hex code.
      embed-color: "#FFD555"

    # The format of the message sent to Discord
    # %player_name% - The player_name's name, %message% - The message, %server% - The server the player is on (ONLY BUNGEE)
    # %luckperms_prefix% - The prefix of the player from LuckPerms, %luckperms_suffix% - The suffix of the player from LuckPerms
    staffchat-format: "**%player_name%**: %message%"

    # The message that is sent to Discord when a player with the "betterstaffchat.messages.join" permission joins
    # %player_name% - The player's name, %server% - The server the player is on (ONLY BUNGEE)
    # %luckperms_prefix% - The prefix of the player from LuckPerms, %luckperms_suffix% - The suffix of the player from LuckPerms
    staffchat-join: "%player_name% **joined** the network"

    # The message that is sent to Discord when a player with the "betterstaffchat.messages.leave" permission leaves
    # %player_name% - The player's name, %server% - The server the player is on (ONLY BUNGEE)
    # %luckperms_prefix% - The prefix of the player from LuckPerms, %luckperms_suffix% - The suffix of the player from LuckPerms
    staffchat-leave: "%player_name% **left** the network"

    # The message that is sent to Discord when a player with the "betterstaffchat.messages.switch" permission servers/worlds
    # %player_name% - The player's name, %from% - The server/world the player left, %to% - The server/world the player joined
    # %luckperms_prefix% - The prefix of the player from LuckPerms, %luckperms_suffix% - The suffix of the player from LuckPerms
    staffchat-switch: "%player_name% **switched** from **%from%** to **%to%**"

commands: # Options for commands | Aliases can not be the same, nor can they be any base command.
  staffchat: # /staffchat command
    aliases: [sc, schat]
  mutestaffchat: # /mutestaffchat command
    aliases: [mutesc, scmute, scm, msc, ignorestaffchat]
  togglestaffchat: # /togglestaffchat command
    aliases: [tsc, sct, sctoggle, staffchattoggle, togglesc]

# Disable this to stop the plugin checking for updates on startup
check-for-updates: true

# Error reporting - Sends anonymous details about the error to the developers.
error-reporting: true

# Don't touch unless you know what you are doing
debug: false

# no touchy me please [DO NOT TOUCH AS IT CAN BREAK YOUR CONFIG]
config-version: 5