name: Bug Report
description: Report a bug with BetterStaffChat.
labels: 'bug: unconfirmed'
body:
- type: markdown
  attributes:
    value: |
      If you are fully sure that what you are reporting is a bug, and can be re-produced, check the tickmark below.
      - [ ] I agree that the bug I am providing can be reproduced 
- type: input
  attributes:
    label: "What version of the plugin are you using"
    description: Please provide the version of BetterStaffChat you are using by providing it below. (`/version BetterStaffChat`)
  validations:
    required: true
- type: textarea
  attributes:
    label: Error Log / Stack Trace
    description: If your bug has a console error, please provide the log here.

- type: textarea
  attributes:
    label: What is the bug
    description: Describe what the bug is.
    placeholder: |
      Example: "When running /nuke after putting everyone into adventure mode, there aren't any explosions..."
  validations:
    required: true
- type: textarea
  attributes:
    label: How to reproduce
    description: Provide steps on how to reproduce/recreate the bug.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual behaviour
    description: Explain what happens with the bug.
  validations:
    required: true    
- type: textarea
  attributes:
    label: Expected behaviour
    description: Explain what should normally happen.
  validations:
    required: true
